/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CounterImport } from './routes/counter'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const CounterWithMemoPropsLazyImport = createFileRoute(
  '/counter-with-memo-props',
)()
const CounterWithMemoCallbackLazyImport = createFileRoute(
  '/counter-with-memo-callback',
)()
const CounterWithMemoLazyImport = createFileRoute('/counter-with-memo')()
const CounterWithCallbackLazyImport = createFileRoute(
  '/counter-with-callback',
)()
const CounterAloneLazyImport = createFileRoute('/counter-alone')()

// Create/Update Routes

const CounterWithMemoPropsLazyRoute = CounterWithMemoPropsLazyImport.update({
  path: '/counter-with-memo-props',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/counter-with-memo-props.lazy').then((d) => d.Route),
)

const CounterWithMemoCallbackLazyRoute =
  CounterWithMemoCallbackLazyImport.update({
    path: '/counter-with-memo-callback',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/counter-with-memo-callback.lazy').then((d) => d.Route),
  )

const CounterWithMemoLazyRoute = CounterWithMemoLazyImport.update({
  path: '/counter-with-memo',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/counter-with-memo.lazy').then((d) => d.Route),
)

const CounterWithCallbackLazyRoute = CounterWithCallbackLazyImport.update({
  path: '/counter-with-callback',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/counter-with-callback.lazy').then((d) => d.Route),
)

const CounterAloneLazyRoute = CounterAloneLazyImport.update({
  path: '/counter-alone',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/counter-alone.lazy').then((d) => d.Route))

const CounterRoute = CounterImport.update({
  path: '/counter',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/counter': {
      id: '/counter'
      path: '/counter'
      fullPath: '/counter'
      preLoaderRoute: typeof CounterImport
      parentRoute: typeof rootRoute
    }
    '/counter-alone': {
      id: '/counter-alone'
      path: '/counter-alone'
      fullPath: '/counter-alone'
      preLoaderRoute: typeof CounterAloneLazyImport
      parentRoute: typeof rootRoute
    }
    '/counter-with-callback': {
      id: '/counter-with-callback'
      path: '/counter-with-callback'
      fullPath: '/counter-with-callback'
      preLoaderRoute: typeof CounterWithCallbackLazyImport
      parentRoute: typeof rootRoute
    }
    '/counter-with-memo': {
      id: '/counter-with-memo'
      path: '/counter-with-memo'
      fullPath: '/counter-with-memo'
      preLoaderRoute: typeof CounterWithMemoLazyImport
      parentRoute: typeof rootRoute
    }
    '/counter-with-memo-callback': {
      id: '/counter-with-memo-callback'
      path: '/counter-with-memo-callback'
      fullPath: '/counter-with-memo-callback'
      preLoaderRoute: typeof CounterWithMemoCallbackLazyImport
      parentRoute: typeof rootRoute
    }
    '/counter-with-memo-props': {
      id: '/counter-with-memo-props'
      path: '/counter-with-memo-props'
      fullPath: '/counter-with-memo-props'
      preLoaderRoute: typeof CounterWithMemoPropsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  CounterRoute,
  CounterAloneLazyRoute,
  CounterWithCallbackLazyRoute,
  CounterWithMemoLazyRoute,
  CounterWithMemoCallbackLazyRoute,
  CounterWithMemoPropsLazyRoute,
})

/* prettier-ignore-end */
